name: "ci"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Docker image for testing
        run: docker build -t meu-app/laravel:test .

      - name: Run Tests with Docker Compose
        run: |
          DOCKER_COMPOSE="docker compose -f docker-compose.ci.yml --env-file .env.ci"
          $DOCKER_COMPOSE up -d

          sleep 5

          $DOCKER_COMPOSE exec -T app cp .env.ci .env
          $DOCKER_COMPOSE exec -T app php artisan key:generate
          $DOCKER_COMPOSE exec -T app php artisan migrate --force --seed
          $DOCKER_COMPOSE exec -T app ./vendor/bin/phpunit
